### ISSUE TITLE
A great package! Have you finished development?

### ISSUE THREAD

**Issue by jxshen311** [SigurdJanson/ccf21#3]
Hi SigurdJanson,

I came across your github repo as I search for ccf functions. Your goals look really useful! Have you finished the project? I look forward to using it!

Best,
Jiaxian

**Comment by SigurdJanson** [comment]
Thank you, Jiaxian, for you interest. Sorry for the late answer. I have neglected this project for quite a while and had to wrap my head around it, before I respond. 

I decided to put it on "experimental", still. Once I started converting it to a package I noticed a few mistakes. Now I fixed most of them, but I there are still a few things to do. If you know anyone who might assist, I would appreciate it and it would speed things up because I cannot make any promises by when I'll get it done.

Now, I fixed most of it. Here is what still needs to be done:
* Fix bug #2 
* Improve test coverage for `as.matrix` and the plots
* Improve tests altogether

**Comment by SigurdJanson** [comment]
Good morning Jiaxian,

I have fixed the last bug, added some more tests, and, finally, put the status on stable. 

I still think that it would not hurt to have more tests. In case you have data sets for which you know the outcome, that would be a great contribution. But all in all the API is stable.

WIth this latest update I'll close this issue.

Thank you for your interest,
Jan

**Comment by jxshen311** [comment]
Hi @SigurdJanson,

Thank you for your response and for taking the time and effort to make it a stable and ready-to-use tool! My daily research goal pivoted a bit in the past weeks. But once I pick up the ccf analysis, I'll keep the testing needs in mind and perform additional tests if my datasets suit the needs.

Thanks again for developing this important tool!

Best,
Jiaxian
